services:
  - type: web
    name: landslide-ml-service
    runtime: python
    rootDir: ml-service
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
